Rephrase mount error as missing image error
When starting with a non-existent image, I still see:

  mount: special device ignored-by-overlayfs does not exist

The half-build container is cleaned up, but this is still an obtuse
error.

This happens because the non-existent image directory is passed right
through to the "mount" command (see lowerdir):

    mount -t overlay \
      -o lowerdir=/var/cookie-cutter/images/non-existent-image/diff \
      -o upperdir=/var/cookie-cutter/containers/tmp.19943/diff \
      -o workdir=/var/cookie-cutter/containers/tmp.19943/work
      ignored-by-overlayfs \
      /var/cookie-cutter/containers/tmp.19943/filesystem

Handle the error better by printing a more specific error message that
points to the earlier problem of trying to use an image that doesn't
exist.

diff --git a/bin/cc-create b/bin/cc-create
--- a/bin/cc-create
+++ b/bin/cc-create
@@ -23,6 +23,10 @@ echo "$image_name" > "$container/from"
 list_layers () {
   local image_name="$1"
   local image="/var/cookie-cutter/images/$image_name"
+  if ! [ -d "$image" ]; then
+    echo "Image not found: $image_name" >&2
+    return 1
+  fi
   echo -n "$image/diff"
   if [ -f "$image/from" ]; then
     echo -n ":"
@@ -32,8 +36,9 @@ list_layers () {
 
 # Kernels before Linux 4.0 would need "overlayfs" instead of
 # "overlay" and can only support one lowerdir.
+layers="$(list_layers "$image_name")"
 mount -t overlay \
-    -o "lowerdir=$(list_layers "$image_name")" \
+    -o "lowerdir=$layers" \
     -o "upperdir=$container/diff" \
     -o "workdir=$container/work" \
     ignored-by-overlayfs \
