Improve error message for missing cc-run command
When the command for cc-run is missing, the usage block isn't shown and
instead the "env" command prints the current environment.  The command
exits successfully.  This failure mode is hard to understand at a glance
if it is noticed at all.

When the command is missing in such a way that "env" would print its
environment, print an error and exit with non-zero status.

diff --git a/bin/cc-run b/bin/cc-run
--- a/bin/cc-run
+++ b/bin/cc-run
@@ -9,6 +9,11 @@ case "$1" in
     ;;
 esac
 
+if [ -z "$2" ]; then
+  echo "Missing command to run." >&2
+  exit 1
+fi
+
 container_name="$1"
 container="/var/cookie-cutter/containers/$container_name"
 shift 1
